#生产环境配置

server:
  # 服务端口
  port: 5000

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: "root"
    password: "g3f3kjFgg22"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.248.62:3306/paimai_car?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8

# 开启权限拦截
auth:
  enabled: true

# 开启登录要求验证码
login-captcha:
  enabled: false
  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"

# 开启请求日志记录
request-log:
  enabled: true

lin:
  #文件上传配置
  file:
    # 文件服务域名
    domain: http://81.70.248.62/service/
    # 服务器文件路径
    serve-path: /deploy/paimai/assets/**
    # 本地文件保存位置
    store-dir: /deploy/paimai/assets/

